stages:
  - build

variables:
  DOCKER_IMAGE: registry.gitlab.com/debrian11-group/pi-arduino-bot/container_bot
  TAG: "1.0"

build_container:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE:$TAG DockerFile/
    - docker push $DOCKER_IMAGE:$TAG

# 7/11/2025 Initial method of creating container with the docker file
stages:
  - build

variables:
  DOCKER_IMAGE: registry.gitlab.com/debrian11-group/pi-arduino-bot/container_bot
  TAG: "1.0"

build_container:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE:$TAG DockerFile/
    - docker push $DOCKER_IMAGE:$TAG
