FROM python:3.11-slim

WORKDIR /app

COPY working_network_comms_6_16/hello-world.py ./
COPY working_network_comms_6_16/modules/ ./modules/

RUN pip install pyserial

CMD ["python3", "hello-world.py"]
